apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: todoapp
spec:
    containers:
    - name: busybox
      # I use this because provided image (ikulyk404/busyboxplus:curl) is built for arm64 architecture
      image: curlimages/curl
      command: ["sh", "-c", "sleep 3600"]
